version: "3.9"

services:
  mysql:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "password"
      ports:
        - "3306"
      volumes:
        - ./database/:/docker-entrypoint-initdb.d
  app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      restart: on-failure